Add support for representing higher-order relationship types
gregr/first-order-miniKanren pull request #4
Opened 2024-02-02 06:39 UTC by pinnouse

This draft pull request currently adds support for the diseq relation, as well as fixing up some of the current code base.

Ongoing: to implement the other relations to be represented

2024-02-02 18:27 UTC, gregr requested changes
Looks good so far.

I'd prefer if you adjust your editor to use 2-space indents in situations where it's currently using 1-space, or else there will be whitespace-churning changes when other people edit this code in the future.

`fresh` should be indented like a binding form, as with `define`, `let`, `lambda`, etc.

Your indentation fixes for `if` are fine, though.

2024-02-02 18:27 UTC, gregr commented on common.rkt
> +  (let* ((sub (if (state? st) (state-sub st) st)) (tm (walk tm sub)))
`walk*` doesn't need a state, just a substitution.  Let's change the callers to always pass a substitution.

2024-02-02 18:27 UTC, gregr commented on tools.rkt
> +         (`(,st . #f) (pause st (== t1 t2)))
`unify` should never return a pair.  So we only need the new case you added.

2024-02-02 18:27 UTC, gregr commented on examples.rkt
> +           (appendo b c bc)))))
`fresh` is a variable-binding form (similar to `let` or `lambda`), so its body should not be indented so much.  Can you adjust your editor's config to have it use the original indentation?

2024-02-02 18:27 UTC, gregr commented on examples.rkt
> + (run*/step step (p q) (appendo p q '(1 2 3 4 5)))
Is it possible to adjust your editor to use 2-space indents in this situation?

2024-02-02 18:27 UTC, gregr commented on examples.rkt
> -    ((fresh (first rest prefix)
2-space indents for `conde` as well.

2024-02-02 18:27 UTC, gregr commented on tools.rkt
> +         (`(,st . #f) (pause st (=/= t1 t2)))
`disunify` should never return a pair.

2024-02-09 15:57 UTC, gregr requested changes
Thanks, the indentation looks better now.

I know it's not code you were involved with, but I noticed this definition is inconsistent with how `walk*` is defined:
```
(define (walked-term t st) (walk* t (state-sub st)))
```

Either `walk*` should be changed to take just a substitution, which is all it really needs, or all callers of `walk*` need to pass it a state.  Although fixing `walk*` is nicer in the long run, I'm fine with the expedient approach if you prefer.

2024-02-09 17:22 UTC, pinnouse commented
Updated `walk*` to take only substitutions, and all calls to `walk*` to use to pass the substitution instead of state.

2024-02-09 18:01 UTC, gregr approved these changes
Looks good.  Thanks for fixing `walk*` too.

2024-02-09 18:01 UTC, merged