Refactor more structure-based approach to explore/stream
gregr/first-order-miniKanren pull request #5
Opened 2024-02-15 05:32 UTC by pinnouse

This pull request factors out common pretty-printing from explore/stream and adds a new structure called explore-stream which is used in explore-state/stream, replicating the same behaviour, but using the structure-first approach and offloading printing to separate functions.

2024-02-15 16:40 UTC, gregr requested changes
The new `explore-state` actuation (`explore-state/make-choice` and `explore-state/make-choices`) and driver loop (`explore-state/stream`) look fine so far, though see the inline comments about naming conventions.

The only real issue is that the pretty-printing logic should not be globally shared like this.  What we want is a driver loop that takes its pretty-printing and user-input policy as a parameter.  More detail in the comments.

2024-02-15 16:40 UTC, gregr commented on tools.rkt
> +(define (explore-state/stream step qvars strm)
We also want to add another parameter for the interaction policy that determines how interaction I/O works.

For organizing your experiments, you really want to maintain multiple policies to see what impact each of them has on the agent's performance.  Being able to swap policies easily is important.

We can also redefine `explore/stream` later, having it call your new driver with a textual pretty-print-and-read interaction policy that mimics the current behavior.

2024-02-15 16:40 UTC, gregr commented on tools.rkt
> +         (read-line)
Keeping in mind the separation described earlier, between updating the state and presentation + receiving of input, this driver should not include any specific strings or printing, and should not use `read` directly. All of those decisions should come from the policy parameter.

2024-02-15 16:40 UTC, gregr commented on tools.rkt
> +(define (explore-state/stream step qvars strm)
Also, this isn't operating on an `explore-state` input, so the name isn't appropriate.  Maybe choose something like `drive/stream` instead.

2024-02-26 19:07 UTC, gregr requested changes
Thanks for the update.

I think there's some confusion about the purpose of separating the driver and policies.  The driver should be carrying out all manipulation of the exploration state.  The policies should define a user interface for displaying the state and receiving commands from the user, then sending those commands to the driver for execution.

This separation is intended to reduce the footprint of future changes while carrying out experiments.  We should be able to swap UIs without changing the exploration code, and we we should be able to adjust the exploration code without large effects on the UI.

It looks like your zipper implementation is on the right track, but could potentially be simplified.  There are more parts than I'd expect to see for a zipper.  If the `explore-loc` is necessary on top of both an `explore-node` and an `explore-context`, an explanation would help.

Please also remove problematic comments and fix indentation.

2024-02-28 01:07 UTC, pinnouse commented on tools.rkt
> +(struct explore-loc (tree context) #:prefab)
I found according to what I read from Wikipedia on zippers and the 2 resources on a tree in Haskell:
- https://wiki.haskell.org/Zipper
- https://learnyouahaskell.com/zippers
the zipper technique stores the actual object that is in focus, and the context that the focused object comes from

2024-02-28 14:52 UTC, gregr commented on tools.rkt
> +(struct explore-loc (tree context) #:prefab)
Right, that's two things.  I see you have these three things:
- `explore-context`
- `explore-node`
- `explore-loc`

What role does each one play in the zipper?

2024-02-29 00:59 UTC, pinnouse commented on tools.rkt
> +(struct explore-loc (tree context) #:prefab)
The "two" you would use for zipper are the explore-node (tree in focus), and explore-context (tree with hole). The explore-loc is a struct that just allows the two to be transported together, it's essentially an ordered pair: tree pointing to the node, context pointing to the context.

2024-02-29 18:10 UTC, gregr requested changes
Thanks, almost there.  Just a few small issues to fix in naming, indentation, and reverting `explore/stream`.

2024-02-29 18:10 UTC, gregr commented on tools.rkt
> +(struct explore-loc (tree context) #:prefab)
Thanks, that makes sense now.

2024-02-29 18:10 UTC, gregr commented on tools.rkt
> +            (explore-choice s step (- input 1))]
Thanks, this looks good now.  Later, if we expand the actions an agent may take, we may have to give more structure to the commands coming from the policy.  But looking for `integer?` vs. `u` is fine for now.

The indentation should have another space.

2024-02-29 18:21 UTC, pinnouse commented on tools.rkt
> +(struct explore-parent-context (index siblings choices context) #:prefab)
That's correct it does refer to its parent context, I am afraid of getting too verbose with the naming; accessing the parent context might look like explore-context-parent-context

2024-02-29 21:01 UTC, gregr commented on tools.rkt
> +(struct explore-parent-context (index siblings choices context) #:prefab)
I think `parent` is still better than `context`, and it would only lead to the accessor name `explore-context-parent`.

2024-02-29 23:22 UTC, gregr approved these changes
Looks good.  Thanks for all the iterating.

2024-02-29 23:23 UTC, merged